name: blogverse
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-alpha.1
  appwrite: ^13.0.0
  provider: ^6.0.0   
  http: ^1.2.2
  flutter_web_auth: ^0.5.0
  flutter_svg: ^2.0.10+1
  intl: ^0.20.1
  file_picker: ^5.2.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

assets:
  - .env
